server:
  port: 8081

spring:
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  typeEnumsPackage: com.project.blog.enums